version: '3'

tasks:
  clear:
    cmd: rm -r gen/go/linker/v2
  gen_v1:
    cmd: protoc -I proto proto/linker/v1/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  gen_v2:
    cmd: protoc -I proto proto/linker/v2/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
