version: '3'

tasks:
  clear:
    cmd: rm -r gen/go/*
  gen:
    cmd: protoc -I proto proto/linker/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative